POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "hieu1",
    "password": "1234"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "hieu",
    "password": "1234"
}

###

POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjQ3ZWNkYzBhMGI0ZGQ0NmJmZGE4ODMiLCJpYXQiOjE2NDg5NTAwODJ9.WjRaL4BtZ4xgYc0WK8yyTO43FAvL2t20gJh8UVyhJFQ

{
    "title": "hieu todo",
    "description": "hieuthu",
    "url": "shopee.com",
    "status": "LEARNING"
}